apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-v2
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v2
  template:
    metadata:
      labels:
        app: employees
        version: v2
    spec:
      containers:
      - name: webapp
        image: 584918656742.dkr.ecr.us-east-1.amazonaws.com/ass2_repository:IMAGE_TAG_2
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: "password"