apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replica
  namespace: sqldb
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 584918656742.dkr.ecr.us-east-1.amazonaws.com/ass2_repository:my_db_latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: DBPWD
          value: "password"
        - name: DBUSER
          value: "root"
        - name: DBHOST
          value: "mysql-service.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        ports:
        - containerPort: 3306