apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: sqldb
  labels:
    app: sqldb
spec:
  containers:
    - name: mysql
      image: 584918656742.dkr.ecr.us-east-1.amazonaws.com/ass2_repository:my_db_latest
      env:
        - name: DBPWD
          value: "password"
        - name: DBUSER
          value: "root"
        - name: DBHOST
          value: "mysql-service.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
      ports:
        - containerPort: 3306